export const DARK_MODE_BACKGROUND_COLOR = `#141414`
export const LIGHT_MODE_BACKGROUND_COLOR = `#efece3`

export const TAR_BAR_ICON_FONT_SIZE = 25
export const TAB_BAR_TITLE_FONT_SIZE = 14
export const TAB_BAR_TEXT_COLOR_ACTIVE = "#2c528c"
export const TAB_BAR_TEXT_COLOR_INACTIVE = "#404040"

export const HORIZONTAL_APP_LIST_TITLE_FONT_SIZE = 23
export const HORIZATION_APP_LIST_LAST_UPDATE_FONT_SIZE = 16
export const HORIZATION_APP_LIST_LAST_UPDATE_FONT_COLOR = "#808080"
export const HORIZONTAL_ITEM_FONT_SIZE = 14
export const HORIZONTAL_ITEM_FONT_COLOR = "white"

export const VERTICAL_ITEM_INDEX_FONT_COLOR = "#a6a6a6"
export const VERTICAL_ITEM_INDEX_FONT_SIZE = 25
export const VERTICAL_ITEM_FONT_SIZE = 16
export const VERTICAL_ITEM_FONT_COLOR = "white"

export const RATING_STAR_FONT_SIZE = 14
export const RATING_STAR_FONT_COLOR = "#ffa31a"
export const RATING_COUNT_FONT_SIZE = 14
export const RATING_COUNT_FONT_COLOR = "#808080"

export const ARROW_UP_BUTTON_FONT_SIZE = 50
export const ARROW_UP_BUTTON_FONT_COLOR = "rgba(128, 128, 128, 0.5)"

export const FETCH_FAILURE_FONT_SIZE = 18
export const FETCH_FAILURE_FONT_COLOR = "#2c528c"